### ISSUE TITLE
[DRC-810] [Bug] Errors when running Profile/Value diff

### ISSUE THREAD

**Issue by alejobs** [DataRecce/recce#459]
### Current Behavior

For some changes, whenever I run Profile/Value diff I get the following error:
`INFO:     ::1:63695 - "GET /api/runs/c46223a3-ebac-4f8f-8ba2-724017890d74/wait?timeout=2 HTTP/1.1" 200 OK
Future exception was never retrieved
future: <Future finished exception=TypeError("'<' not supported between instances of 'NoneType' and 'NoneType'")>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abuxeres/code/dbt-models/.venv/lib/python3.11/site-packages/recce/apis/run_func.py", line 151, in fn
    raise e
  File "/Users/abuxeres/code/dbt-models/.venv/lib/python3.11/site-packages/recce/apis/run_func.py", line 144, in fn
    result = task.execute()
             ^^^^^^^^^^^^^^
  File "/Users/abuxeres/code/dbt-models/.venv/lib/python3.11/site-packages/recce/tasks/histogram.py", line 335, in execute
    min_value = min(min_value, min_max_curr[0][0])`

or this:
`INFO:     ::1:63722 - "GET /api/runs/5202adc1-147d-413d-8cca-c26a638234a1/wait?timeout=2 HTTP/1.1" 200 OK
Future exception was never retrieved
future: <Future finished exception=InvalidOperation([<class 'decimal.InvalidOperation'>])>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abuxeres/code/dbt-models/.venv/lib/python3.11/site-packages/recce/apis/run_func.py", line 151, in fn
    raise e
  File "/Users/abuxeres/code/dbt-models/.venv/lib/python3.11/site-packages/recce/apis/run_func.py", line 144, in fn
    result = task.execute()
             ^^^^^^^^^^^^^^
  File "/Users/abuxeres/code/dbt-models/.venv/lib/python3.11/site-packages/recce/tasks/histogram.py", line 336, in execute
    max_value = max(max_value, min_max_curr[0][1])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]`

### Expected Behavior

I should see a more clear error and be able to fix the issue

### Steps To Reproduce

1. Generate a state file in Github Actions
2. Download the state file
3. Run: recce server --review /Users/abuxeres/Downloads/recce_state.json

### Environment

- recce: 0.36.0
- OS: MacOS 14.7
- Python: 3.11.6
- Data Warehouse: Snowflake
- dbt: 1.8.0

<sub>[DRC-810](https://linear.app/recce/issue/DRC-810/[bug]-errors-when-running-profilevalue-diff)</sub>

**Comment by popcornylu** [comment]
Hi @alejobs, 

Thanks for your response. We’ll try to reproduce the issue to investigate further.

**Comment by popcornylu** [comment]
![image.png](https://uploads.linear.app/b2e49c73-01e0-44d0-b5bc-3747f0582afa/13e92ea5-cc89-4cfb-af98-755ab4db95ce/fc95742f-7ba7-4bf2-a813-82b0d9582245?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2IyZTQ5YzczLTAxZTAtNDRkMC1iNWJjLTM3NDdmMDU4MmFmYS8xM2U5MmVhNS1jYzg5LTRjZmItYWY5OC03NTVhYjRkYjk1Y2UvZmM5NTc0MmYtN2JhNy00YmYyLWE4MTMtODJiMGQ5NTgyMjQ1IiwiaWF0IjoxNzI5NTgwNzIwLCJleHAiOjE3NjExMTY3MjB9.ycU9O6fXg_4hv3PGr1oVvAMwl8STzXRVJD_EZeIcJ7A)

The error is found when there is no records of one side.
