### ISSUE TITLE
[DRC-861] [Bug] Abstract class SqlmeshAdapter can't be instantiated when trying to start recce server

### ISSUE THREAD

**Issue by db-tycoon-stephen** [DataRecce/recce#473]
### Current Behavior

This command fails
`recce server --sqlmesh --sqlmesh-envs prod:dev`
with the following error
`  File "/Users/ssciortino/.pyenv/versions/3.12.3/envs/recce/lib/python3.12/site-packages/recce/adapter/sqlmesh_adapter.py", line 90, in load
    return cls(context=context, base_env=base_env, curr_env=curr_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class SqlmeshAdapter without an implementation for abstract method 'select_nodes'`

### Expected Behavior

Recce server should run without error.

### Steps To Reproduce

1. Install recce in a virtualenv (3.12.3)
2. Install sqlmesh[duckdb] in virtualenv
3. Create prod and dev environments in sqlMesh
4. Run command above

### Relevant log output

```shell
(recce) *[main][~/Projects/recce]$ recce server --sqlmesh --sqlmesh-envs prod:dev
────────────────────────────────────────────────────────────────────────────────────────────────────── Recce Server ──────────────────────────────────────────────────────────────────────────────────────────────────────
INFO:     Started server process [86865]
INFO:     Waiting for application startup.
WARNING:  SQLMesh adapter is still in EXPERIMENTAL mode.
ERROR:    Traceback (most recent call last):
  File "/Users/ssciortino/.pyenv/versions/3.12.3/envs/recce/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/Users/ssciortino/.pyenv/versions/3.12.3/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssciortino/.pyenv/versions/3.12.3/envs/recce/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/Users/ssciortino/.pyenv/versions/3.12.3/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssciortino/.pyenv/versions/3.12.3/envs/recce/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/Users/ssciortino/.pyenv/versions/3.12.3/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssciortino/.pyenv/versions/3.12.3/envs/recce/lib/python3.12/site-packages/recce/server.py", line 48, in lifespan
    ctx = load_context(**kwargs, state_loader=state_loader)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssciortino/.pyenv/versions/3.12.3/envs/recce/lib/python3.12/site-packages/recce/core.py", line 247, in load_context
    recce_context = RecceContext.load(**kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssciortino/.pyenv/versions/3.12.3/envs/recce/lib/python3.12/site-packages/recce/core.py", line 40, in load
    context.adapter = SqlmeshAdapter.load(**kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssciortino/.pyenv/versions/3.12.3/envs/recce/lib/python3.12/site-packages/recce/adapter/sqlmesh_adapter.py", line 90, in load
    return cls(context=context, base_env=base_env, curr_env=curr_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class SqlmeshAdapter without an implementation for abstract method 'select_nodes'

ERROR:    Application startup failed. Exiting.
```

### Environment

- recce: 0.39.0
- OS: MacOS Sequoia 15.0
- Python: 3.12.3
- Data Warehouse: DuckDb
- sqlMesh: 0.130.0

<sub>[DRC-861](https://linear.app/recce/issue/DRC-861/[bug]-abstract-class-sqlmeshadapter-cant-be-instantiated-when-trying)</sub>

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I've implemented the missing `select_nodes` method in the `SqlmeshAdapter` class. This method is required as it's an abstract method in the `BaseAdapter` class. The implementation returns an empty set as SQLMesh doesn't have a concept of selecting nodes like dbt does. This should resolve the TypeError when instantiating the SqlmeshAdapter.

I also created pull request: https://github.com/DataRecce/recce/pull/474


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission
