### ISSUE TITLE
[DRC-892] [Bug] <when poetry adding recce, it uninstalls dbt dependency packages, causing dbt to not compile>

### ISSUE THREAD

**Issue by erikchu13** [DataRecce/recce#481]
### Current Behavior

when running poetry add recce, it removes dbt package dependencies 
```
(ba-finance-dbt-py3.11) ➜  ba-finance-dbt git:(data_diff_recce) poetry add recce
Using version ^0.40.0 for recce

Updating dependencies
Resolving dependencies... (5.8s)

Package operations: 21 installs, 0 updates, 6 removals

  - Removing attrs (24.2.0)
  - Removing distlib (0.3.9)
  - Removing jsonschema (4.23.0)
  - Removing jsonschema-specifications (2024.10.1)
  - Removing referencing (0.35.1)
  - Removing rpds-py (0.20.0)
  - Installing sniffio (1.3.1)
  - Installing anyio (4.6.2.post1)
  - Installing smmap (5.0.1)
  - Installing wrapt (1.16.0)
  - Installing deprecated (1.2.14)
  - Installing gitdb (4.0.11)
  - Installing h11 (0.14.0)
  - Installing pynacl (1.5.0)
  - Installing starlette (0.41.2)
  - Installing fastapi (0.115.4)
  - Installing gitpython (3.1.43)
  - Installing itsdangerous (2.2.0)
  - Installing portalocker (2.10.1)
  - Installing py-markdown-table (1.1.0)
  - Installing pygithub (2.5.0)
  - Installing python-multipart (0.0.17)
  - Installing sentry-sdk (2.18.0)
  - Installing uvicorn (0.32.0)
  - Installing watchdog (6.0.0)
  - Installing websockets (14.0)
  - Installing recce (0.40.0)

Writing lock file
```

when I run `dbt compile --target prod`, I get this error
```

(ba-finance-dbt-py3.11) ➜  intacct_models git:(recce_test) ✗ dbt compile --target prod
Traceback (most recent call last):
  File "/Users/erik.chu/Documents/Repositories/ba-finance-dbt/.venv/bin/dbt", line 5, in <module>
    from dbt.cli.main import cli
  File "/Users/erik.chu/Documents/Repositories/ba-finance-dbt/.venv/lib/python3.11/site-packages/dbt/cli/__init__.py", line 1, in <module>
    from .main import cli as dbt_cli  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erik.chu/Documents/Repositories/ba-finance-dbt/.venv/lib/python3.11/site-packages/dbt/cli/main.py", line 14, in <module>
    from dbt.cli import requires, params as p
  File "/Users/erik.chu/Documents/Repositories/ba-finance-dbt/.venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 5, in <module>
    from dbt_common.clients.system import get_env
  File "/Users/erik.chu/Documents/Repositories/ba-finance-dbt/.venv/lib/python3.11/site-packages/dbt_common/clients/system.py", line 1, in <module>
    import dbt_common.exceptions.base
  File "/Users/erik.chu/Documents/Repositories/ba-finance-dbt/.venv/lib/python3.11/site-packages/dbt_common/exceptions/__init__.py", line 1, in <module>
    from dbt_common.exceptions.base import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erik.chu/Documents/Repositories/ba-finance-dbt/.venv/lib/python3.11/site-packages/dbt_common/exceptions/base.py", line 6, in <module>
    from dbt_common.dataclass_schema import ValidationError
  File "/Users/erik.chu/Documents/Repositories/ba-finance-dbt/.venv/lib/python3.11/site-packages/dbt_common/dataclass_schema.py", line 3, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
```

### Expected Behavior

dbt to still compile after installing recce

### Steps To Reproduce

see above

### Relevant log output

```shell
pyproject.toml file

[tool.poetry]
name = "ba-finance-dbt"
version = "3.32.0"
description = ""
readme = "README.md"
# package-mode = false

[[tool.poetry.source]]
name = "codeartifact-prod"
url = aws code artifact
priority = 'primary'

[[tool.poetry.source]]
name = "codeartifact-dev"
url = aws code artifact 
priority = 'supplemental'

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
dbt-core = "^1.8.7"
dbt-snowflake = "^1.8.3"
boto3 = "^1.34.45"
montecarlodata = "^0.80.0"
setuptools = "^69.0.3"
recce = "^0.40.0"


[tool.poetry.group.dev.dependencies]
dbt-invoke = "^1.0.0"
sqlfluff = "^2.3.5"
yamllint = "^1.35.1"
black = "^24.2.0"
pylint = "^3.0.3"
bandit = "^1.7.7"
dbt-helper = "^0"
pre-commit = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Environment

- recce: 0.40.0 
- OS: MacOs Sequoia 15.1
- Python: Python 3.11.8
- Data Warehouse: Snowflake
- dbt:  dbt-snowflake 1.8.4  

<sub>[DRC-892](https://linear.app/recce/issue/DRC-892/[bug]-when-poetry-adding-recce-it-uninstalls-dbt-dependency-packages)</sub>

**Comment by even-wei** [comment]
Hi @erikchu13 

Did you tried reinstall all packages by:
```
rm poetry.lock
poetry update
poetry install
```

We have a open source dbt project using DuckDB, [TodoEFC-dbt](https://github.com/DataRecce/TodoFEC-dbt), which uses Poetry as well.
But I cannot reproduce your issue in this project.

Meanwhile, I'm trying to build another one from dbt-labs/jaffle-shop to have a base for better discussion.

**Comment by even-wei** [comment]
Hi @erikchu13 

I create a repo [jaffle-shop-snowflake](https://github.com/DataRecce/jaffle-shop-snowflake/tree/with-poetry) to reproduce the issue but I can run dbt successfully.
Please try to reproduce the issue on branch "with-poetry"
```
git clone git@github.com:DataRecce/jaffle-shop-snowflake.git
cd jaffle-shop-snowflake
git checkout with-poetry
```

FYI:
```
poetry env info

Virtualenv
Python:         3.10.12
Implementation: CPython
Path:           /Users/evenwei/Library/Caches/pypoetry/virtualenvs/jaffle-shop-snowflake-P8JBmzEO-py3.10
Executable:     /Users/evenwei/Library/Caches/pypoetry/virtualenvs/jaffle-shop-snowflake-P8JBmzEO-py3.10/bin/python
Valid:          True

Base
Platform:   darwin
OS:         posix
Python:     3.10.12
Path:       /Users/evenwei/.pyenv/versions/3.10.12
Executable: /Users/evenwei/.pyenv/versions/3.10.12/bin/python3.10
```

```
poetry show | grep jsonschema
jsonschema                 4.23.0      An implementation of JSON Schema val...
jsonschema-specifications  2024.10.1   The JSON Schema meta-schemas and voc...
```

```
dbt compile
02:41:26  Running with dbt=1.8.7
02:41:26  Registered adapter: snowflake=1.8.4
02:41:26  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- seeds.jaffle_shop
02:41:26  Found 13 models, 27 data tests, 6 sources, 19 metrics, 759 macros, 6 semantic models, 3 saved queries, 3 unit tests
02:41:26
02:41:29  Concurrency: 4 threads (target='dev')
02:41:29
```

**Comment by erikchu13** [comment]
Hi Evan,

Thanks for your help. It's been resolved and I'm now using Recce! It was a
Poetry issue - this ticket can be closed.

Best,
Erik
